### ISSUE TITLE
Add a --watch in CLI

### ISSUE THREAD

**Issue by Heziode** [avast/vuei18n-po#3]
Hi,

A `--watch` in CLI can be useful wen we don't want use watcher in code.

**Comment by pavelstudeny** [comment]
This module executes the transformation and finishes. What exactly would the --watch do here? The development of this module was test-driven and the test do their job. Would you like to send a pull request?

**Comment by Heziode** [comment]
I mean a workflow like like so:

- lanch the command: `vuei18n-po --watch --messagesDir=lang translations/*.po`
- edit a `.po` file
- save this `.po` file
- `vuei18n-po` detect a change and so, re-transform files

For a PR, I can take a  look, but I am very busy lately.

**Comment by pavelstudeny** [comment]
I see. Yes this makes sense, although I can't promise any release date for it.

**Comment by pavelstudeny** [comment]
included in 1.3.0 and available on npmjs. many thanks!
